name: Infrastructure Provisioning

on:
  push:
    branches:
      - main
    paths:
      - '*'

jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Provision Infrastructure
        run: |
          
          terraform init